### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ArghyaPal** [coupriec/VideoPredictionICLR2016#2]
@MichaelMathieu 

When I tried   `th test-frame-prediction-on-ucf-rec_gdl.lua`

I got the error:

`gm (GraphicsMagick) binary not found, please install (see www.graphicsmagick.org)	
THCudaCheck FAIL file=/home/dl-box/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=65 error=2 : out of memory
/home/dl-box/torch/install/bin/luajit: /home/dl-box/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /home/dl-box/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:65
stack traceback:
	[C]: in function 'read'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:351: in function </home/dl-box/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/nn/Module.lua:184: in function 'read'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...e/dl-box/torch/install/share/lua/5.1/nngraph/gmodule.lua:495: in function 'read'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/dl-box/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	test-frame-prediction-on-ucf-rec_gdl.lua:59: in main chunk
	[C]: in function 'dofile'
	...-box/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
`

I think the problem is that, I am out of memory. 
Now, from where I can reduce the network size?

**Comment by MichaelMathieu** [comment]
You can try to reduce the batch size.

**Comment by ArghyaPal** [comment]
Thank you @MichaelMathieu for your suggestion. It's working fine now. :-)
